matrix:
  include:
    - language: node_js
      node_js:
        - "lts/*"
      before_script:
        - cd frontend
      cache:
        directories:
          - frontend/node_modules
      script:
        - npm install
        - npm run build
        - npm run test-coverage
      after_success:
        - npm run codecov
    - language: java
      before_script:
        - cd backend
      after_success:
        - bash <(curl -s https://codecov.io/bash)